[test]
preload = ["./test-setup.ts"]
coverage = true
coverageDir = "coverage"
coverageReporter = ["text", "lcov"]
coverageSkipTestFiles = true
coverageThreshold = { global = { branches = 85, functions = 85, lines = 85, statements = 85 } }
